name: build

on: push

jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Check outdated dependencies
      run: go mod tidy -diff
    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest
    - name: Check vulnerabilities
      run: govulncheck ./...

  lint:
    runs-on: ubuntu-latest
    needs: depcheck
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Check format according to gofmt
      run: test -z $(gofmt -l .)
    - name: Install linter
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.5
    - name: Check format according to gofmt
      run: golangci-lint run ./...

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
    - name: Test
      run: go test -v ./...
